---
- name: Crear un nuevo usuario en la VM Linux
  hosts: "{{ _hosts | default('RHEL') }}"
  become: yes  # para usar sudo
  vars:
    nombre_usuario:  "{{ _nuevo_usuario | default('user') }}"
    shell_usuario: /bin/bash
  tasks:
    - name: Crear el usuario
      user:
        name: "{{ nombre_usuario }}"
        shell: "{{ shell_usuario }}"
        state: present
        create_home: yes

    - name: Crear la contraseña del usuario (opcional)
      user:
        name: "{{ nombre_usuario }}"
        password: "{{ 'RedHat12345' | password_hash('sha512') }}"

