---
- name: Create a service account on Microsoft SQL server and then verify the access granted
  hosts: "{{ _hosts | default('windows') }}"
  tasks:
    - name: Create a service account on Microsoft SQL server
      microsoft.ad.user:
        name: SQLService
        upn: "{{ _upn_ }}"
        password: "{{ _password_ }}"
        state: present
        groups:
          set:
            - Domain Admins
            - Enterprise Admins
        update_password: "{{ _update_password_  | default('true')}}"
        password_never_expires: "{{ _password_never_expires_ }}"
        enabled: true
        attributes:
          servicePrincipalName: SQLService@{{ domain_name }}
          userPrincipalName: SQLService@{{ domain_name }}
          displayName: SQLService
          mail: SQLService@{{ domain_name }}
          givenName: SQLService
          sn: SQLService
          company: "{{ company_name }}"
          department: "{{ department_name }}"
          streetAddress: "{{ street_address }}"
          city: "{{ city }}"
          state: "{{ state }}"
          postalCode: "{{ postal_code }}"
          country: "{{ country }}"
          telephoneNumber: "{{ telephone_number }}"
          mobile: "{{ mobile_number }}"
          description: "{{ description }}"
    - name: Verify the access granted
      microsoft.ad.object_info:
        identity: "{{ _identity_ }}"
        properties:
          - memberOf
      register: user_info
    - name: Print the memberOf attribute
      ansible.builtin.debug:
        var: user_info.objects[0].memberOf
